apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello-deployment
  labels:
    app: springboot-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
        - name: springboot-hello
          image: srishtipundir/springboot-hello:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          volumeMounts:
            - mountPath: /app/data      # container ke andar data yahan save hoga
              name: springboot-storage
      volumes:
        - name: springboot-storage
          persistentVolumeClaim:
            claimName: springboot-pvc
