apiVersion: v1
kind: PersistentVolume
metadata:
  name: springboot-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/springboot   # Node ke local path par data store hoga
