apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-service
  labels:
    app: springboot-hello
spec:
  type: NodePort
  selector:
    app: springboot-hello
  ports:
    - protocol: TCP
      port: 8080          # Service port (ClusterIP)
      targetPort: 8080    # Pod ka containerPort
      nodePort: 31000     # NodePort (EC2 se access hoga)
