apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-service
spec:
  type: NodePort
  selector:
    app: springboot-hello
  ports:
    - protocol: TCP
      port: 8080          # Cluster port
      targetPort: 8080    # Pod port
      nodePort: 30080     # EC2 public IP se access
