apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-service
spec:
  type: NodePort
  selector:
    app: springboot-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080   # EC2 public IP se access ke liye
